//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListaClientesNet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public string Pais { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public string DNI { get; set; }
        public byte Activar { get; set; }
        public string Empresa { get; set; }
        public string Twitter { get; set; }
        public string Intereses { get; set; }
        public string Genero { get; set; }
    }
}
